# Generated by Django 3.0.8 on 2021-11-18 01:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_remove_profile_is_admin'),
        ('meals', '0003_meal_meal_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('special_requirements', models.TextField(blank=True, max_length=200, null=True)),
                ('order_status', models.CharField(choices=[('new', 'New'), ('on_kitchen', 'Processing'), ('cancelled', 'Cancelled')], default='New', max_length=200)),
                ('meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meals.Meal')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
    ]
