# Generated by Django 3.0.8 on 2021-11-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='special_requirements',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
