# Generated by Django 3.0.8 on 2021-11-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211114_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('new', 'New'), ('on_kitchen', 'Processing'), ('cancelled', 'Cancelled')], default='New', max_length=200),
        ),
    ]
